### ISSUE TITLE
Not sure why this happens when i run it

### ISSUE THREAD

**Issue by dinvisible1** [idleice/whatsapp-analyzer#1]
root@Kali:~/whatsapp-analyzer# python analyzer.py vibes_chat.txt
Traceback (most recent call last):
  File "analyzer.py", line 334, in <module>
    members = sorted(chat.process(), key=lambda m: sum(m.days))
  File "analyzer.py", line 96, in process
    self._rmnl()
  File "analyzer.py", line 90, in _rmnl
    prev = prev[:-1] + ' ' + msg
TypeError: 'NoneType' object has no attribute '__getitem__'
root@Kali:~/whatsapp-analyzer#

**Comment by dinvisible1** [comment]
root@Kali:~/whatsapp-analyzer# python analyzer.py vibes_chat.txt
Traceback (most recent call last):
  File "analyzer.py", line 334, in <module>
    members = sorted(chat.process(), key=lambda m: sum(m.days))
  File "analyzer.py", line 96, in process
    self._rmnl()
  File "analyzer.py", line 90, in _rmnl
    prev = prev[:-1] + ' ' + msg
TypeError: 'NoneType' object has no attribute '__getitem__'
root@Kali:~/whatsapp-analyzer#

**Comment by empicano** [comment]
The error happens while formatting the chat file. I reproduced it by adding a blank line at the start of the chat file. I added an additional condition, the problem should be resolved now.
